### ISSUE TITLE
There no named export "Translate" 

### ISSUE THREAD

**Issue by damianobarbati** [googleapis/nodejs-translate#107]
Here => https://github.com/googleapis/nodejs-translate/blob/master/samples/quickstart.js#L20

The quickstart is wrong, it should be: 
```
const Translate = require('@google-cloud/translate');
```

**Comment by fhinkel** [comment]
Confirmed. `npm i` installs `translate-1.1.0` where you need to do `const Translate = require('@google-cloud/translate');`. 

Can we release `translate-2.1.0` so that the Readme matches what's on npm?

`

```
const translate = new Translate({
                  ^

TypeError: Translate is not a constructor
    at Object.<anonymous> (/Users/franzih/translate-quick/quick.js:8:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by JustinBeckwith** [comment]
Sure! Let's try this again:
https://github.com/googleapis/nodejs-translate/pull/114

**Comment by fhinkel** [comment]
It worked. @damianobarbati thanks for opening the issue 😻 . If you upgrade the dependency to `2.1.0`, the Quickstart matches it.
