### ISSUE TITLE
System tests fail with request error

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-translate#108]
This was getting masked by a problem with the logic in the system tests, which I'm about to fix.  CI is failing for this here:
https://circleci.com/gh/googleapis/nodejs-translate/3384

It looks like this is related to the transition to `teeny-request`:

```
1) translate
       authentication
         should use an API key to authenticate:
     TypeError: Cannot read property 'defaults' of undefined
      at Util.makeRequest (node_modules/@google-cloud/common/src/util.ts:624:45)
      at Translate.request (src/index.ts:551:10)
      at Translate.getLanguages (src/index.ts:354:10)
      at Translate.wrapper (node_modules/@google-cloud/promisify/src/index.ts:73:29)
      at Context.it (system-test/translate.ts:165:17)
```

**Comment by fhinkel** [comment]
I see, we're trying to use `config.request` [here](https://github.com/googleapis/nodejs-common/blob/bcf1ea6ac623cade859b546710ce65f6a8511745/src/util.ts#L624), but we set `config.requestModule` [here](https://github.com/googleapis/nodejs-translate/blob/85faf8213e6941456bc25ce222a922c439188607/src/index.ts#L152).
