### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: The request is missing a valid API key.

### ISSUE THREAD

**Issue by jonathanferreiras** [googleapis/nodejs-translate#435]
Sorry for my English.

So, very poorly explained the use of this library. It only asks for the project id but the error occurs:

UnhandledPromiseRejectionWarning: Error: The request is missing a valid API key.

Why not put the field to place the API Key too ??

I tried to authenticate using:

set GOOGLE_APPLICATION_CREDENTIALS = [PATH]

path would be the available json file.

Even so, this error occurs. Please google you could be more didactic.

The code used was the example on the library's npm website.

Thanks.

**Comment by bcoe** [comment]
@jonathanferreiras could you provide an example of the code you're running? Setting `GOOGLE_APPLICATION_CREDENTIALS` should work, I'm wondering if perhaps there's a slight issue with how the library is instantiated.

**Comment by UnderMountain96** [comment]
javascript solutions
```javascript
process.env.GOOGLE_APPLICATION_CREDENTIALS="[PATH]";
```

**Comment by bcoe** [comment]
@jonathanferreiras please let me know if you're continuing to have issues and we can reopen, make sure that `GOOGLE_APPLICATION_CREDENTIALS` is pointing to a valid service account JSON, and I think you should find things work :ok_hand:

**Comment by Mistic92** [comment]
I have very similar issue when running in WSL2. 
Project is stored on WSL2, vs code is in remote mode. 

```
Message:
  The incoming JSON object does not contain a client_email field
  
  Stack:
  Error: The incoming JSON object does not contain a client_email field
      at JWT.fromJSON (/root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/node_modules/google-auth-library/build/src/auth/jwtclient.js:183:19)
      at GoogleAuth._cacheClientFromJSON (/root/projects/XXXXXXXXXX/node_modules/@google-cloud/translate/node_modules/google-auth-library/build/src/auth/googleauth.js:298:20)
      at GoogleAuth.getClient (/root/projects/XXXXXXXXX/node_modules/@google-cloud/translate/node_modules/google-auth-library/build/src/auth/googleauth.js:479:26)
      at GoogleAuth.authorizeRequest (/root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/node_modules/google-auth-library/build/src/auth/googleauth.js:528:39)
      at Translate.makeAuthenticatedRequest (/root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/node_modules/@google-cloud/common/build/src/util.js:379:28)
      at Translate.request_ (/root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/node_modules/@google-cloud/common/build/src/service.js:131:18)
      at Translate.request (/root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/node_modules/@google-cloud/common/build/src/service.js:142:36)
      at Translate.request (/root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/build/src/v2/index.js:441:19)
      at Translate.detect (/root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/build/src/v2/index.js:187:14)
      at /root/projects/xxxxxxxxxxx/node_modules/@google-cloud/translate/node_modules/@google-cloud/promisify/build/src/index.js:57:28
```

**Comment by imarpit007** [comment]
i am using google cloud translate api for my project but getting "Error in translation ApiError: The request is missing a valid API key."

codes are same as shown in npm google cloud/translate website with little modifications

const {Translate} = require('@google-cloud/translate').v2;
const projectId = 'prokect-id here';
const translate = new Translate({projectId});
async function translateFunction(textFromWeb, targetLanguage) {
    let text = textFromWeb;
    let target = targetLanguage;
    const [translation] = await translate.translate(text, target);
    console.log(`Text: ${text}`);
    console.log(`Translation: ${translation}`);
    return translation;
}

exports.translateApi = async (req, res) => {
    try {
        // The text to translate
        const textFromWeb = [
            "这是一个非常好的API",
            "to jest bardzo dobre API",
            "это очень хороший API",
        ];
        // The target language
        const targetLanguage = 'ru';

        translatedText = await translateFunction(textFromWeb, targetLanguage);
        if (!translatedText){
            return res.send({
                success: false,
                message: "Translation failed."
            });
        }
        return res.send({
            success: true,
            message: "Translated successfully!",
            translatedText: translatedText
        });     
    } catch (error) {
        console.log("Error in translation", error);
        return res.send({
            success: false,
            message: messages.ERROR
        });
    }
};
