### ISSUE TITLE
I want to use this library with node.js 8.9.4

### ISSUE THREAD

**Issue by tinytortoise-dev** [googleapis/nodejs-translate#548]
Currently, my node version is 8.9.4, so I installed this library through this command: 
`npm install --save @google-cloud/translate@legacy-8`

When running this code, I've got an error.
```
const projectId = translation.googleProjectId;
const { Translate } = require('@google-cloud/translate').v2;
const translate = new Translate({ projectId });
const [translatedText] = yield translate.translate(originalText, target);
```

```
(node:53552) ExperimentalWarning: The http2 module is an experimental API.
error:  Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
at Object.<anonymous> (C:\myproject\node_modules\@grpc\grpc-js\build\src\index.js:47:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\myproject\node_modules\node_modules\google-gax\build\src\grpc.js:21:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\myproject\node_modules\node_modules\google-gax\build\src\index.js:18:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

I know the best and straight solution is upgrading my node version. But Is there any tip to use this library with node 8.9.4? Really don't want to change node version if possible.

**Comment by JustinBeckwith** [comment]
Greetings!  Sadly, this isn't something we're going to be able to support.  Modern versions of this library are going to be largely dependent upon `grpc`, which requires `http2`, which didn't go LTS until later versions of Node.js 8.x.  

Node.js 8.x is out of support from the Open JS Foundation, and you're running code that likely has security vulnerabilities :(
https://github.com/nodejs/Release#end-of-life-releases

If you really need to stay on that version of node.js, the last release we had that will work without http2 is going to be `2.1.4`:
https://github.com/googleapis/nodejs-translate/releases/tag/v2.1.4

Hope this helps!
