### ISSUE TITLE
Fail to request translate detect

### ISSUE THREAD

**Issue by phgnam** [googleapis/nodejs-translate#746]
Sometimes I get error when use translate and detect function
```
{ FetchError: request to https://translation.googleapis.com/language/translate/v2/detect failed, reason: connect ECONNREFUSED 203.208.43.65:443
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://translation.googleapis.com/language/translate/v2/detect failed, reason: connect ECONNREFUSED 203.208.43.65:443',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```
Somebody explain to me

**Comment by kweinmeister** [comment]
Hi. Are you on a corporate network with a proxy? If so, can you try setting the environment variable `https_proxy` to your proxy URL?

**Comment by nicain** [comment]
@phgnam were you able to set https_proxy, and if so, did it help?

**Comment by kweinmeister** [comment]
Since we didn't hear back on this issue, we will go ahead and close it. Please feel free to re-open if you have more information.
